#!/bin/bash
# Copyright (c) 2019 Hush developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

NAME=HUSH3

CLI=${KOMODOCLI:-./komodo-cli}
# Debian packages prefix binaries with hush-
# so we prevent conflicting with official komodod
if [ ! -e "$CLI" ]; then
	CLI=hush-komodo-cli
fi
$CLI -ac_name=$NAME "$@"
